apiVersion: v1
kind: Pod
metadata:
  name: sphinx
  labels:
    app: sphinx
spec:
  containers:
  - image: robinhoodis/sphinx:0.0.53
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: Always
    name: sphinx
  restartPolicy: Always
